### ISSUE TITLE
I miss the death toll from v1...

### ISSUE THREAD

**Issue by gaspard** [daenuprobst/dashcoch-v2#7]
Hi there !

Thanks for your contribution to factual information on the covid crisis in Switzerland. I have been keeping an eye on the daily death average from covid since march and really miss this information in the last update.

Just this graph:

![image](https://user-images.githubusercontent.com/21707/101525765-02327d00-398c-11eb-8fce-0c462faa2135.png)

Maybe it's in there and I am missing something ?

Cheers !!

**Comment by MorgeMoensch** [comment]
It's available 😉

In the first graph on the left side, select 'Todesfälle' or 'Fatalities'. Then in the  graph on the right select 'all' and you should see exactly what you would like:
![grafik](https://user-images.githubusercontent.com/62468040/102015729-95d5c600-3d5d-11eb-9a4c-adb231b8bcf4.png)

**Comment by gaspard** [comment]
Oh.. Thanks !
